spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/car
        username: root
        password: root
    cache:
        type: redis
    redis:
        host: 0.0.0.0
        port: 6379

api-ninja:
    key: 0zLP7n7uAq6fat6XANg22g==uj2O8atD56WY0LdX